version: '3'
services:
  react:
    build:
      args:
        - NODE_VER=20.10.0-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - "5173:5173"
      - "24678:24678"
